config/routes.rb
Rails.application.routes.draw do

  resources :students

	root 'students#index'

end

app/models/student.rb
class Student < ActiveRecord::Base

	after_save :clear_cache

	def self.fetch
		students = $redis.get('students')
		if students.nil?
			students = self.all.to_json
			$redis.set('students', students)
		end
		JSON.load(students)
	end

	def clear_cache
		$redis.del('students')
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  def index
		@students = Student.fetch
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Student was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def student_params
      params.require(:student).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.haml
!!!5
%html
	%head
		%meta{ charset: "utf-8" }
		%title Caching with Redis
		= stylesheet_link_tag "application"
		= csrf_meta_tag
	%body
		= yield
	= javascript_include_tag "application"

app/views/students/_form.html.haml
= form_for @student do |f|
  - if @student.errors.any?
    #error_explanation
      %h2= "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      %ul
        - @student.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :age
    = f.number_field :age
  .actions
    = f.submit 'Save'

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %thead
    %tr
      %th Name
      %th Age
      %th
      %th
      %th

  %tbody
    - @students.each do |student|
      %tr
        %td= student['name']
        %td= student['age']
        %td= link_to 'Show', student_path(student['id'])
        %td= link_to 'Edit', edit_student_path(student['id'])
        %td= link_to 'Destroy', student_path(student['id']), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', students_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @student.name
%p
  %b Age:
  = @student.age

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path